import { assertEquals as equals } from "../deps/assert.ts";
import { pluginNames } from "../core/utils/lume_config.ts";

const totalPlugins = Array.from(Deno.readDirSync("plugins")).length;

Deno.test("Plugins list in init", () => {
  equals(pluginNames.length, totalPlugins - 9);

  equals(pluginNames, [
    "attributes",
    "date",
    "code_highlight",
    "decap_cms",
    "fff",
    "eta",
    "extract_date",
    "jsx",
    "json_ld",
    "reading_info",
    "relations",
    "lume_cms",
    "mdx",
    "metas",
    "multilanguage",
    "nav",
    "nunjucks",
    "pagefind",
    "plaintext",
    "prism",
    "pug",
    "remark",
    "robots",
    "sheets",
    "filter_pages",
    "redirects",
    "icons",
    "esbuild",
    "terser",
    "katex",
    "google_fonts",
    "sass",
    "unocss",
    "tailwindcss",
    "postcss",
    "lightningcss",
    "purgecss",
    "source_maps",
    "base_path",
    "resolve_urls",
    "relative_urls",
    "slugify_urls",
    "modify_urls",
    "check_urls",
    "og_images",
    "favicon",
    "svgo",
    "picture",
    "transform_images",
    "inline",
    "sri",
    "validate_html",
    "feed",
    "sitemap",
    "minify_html",
    "brotli",
    "gzip",
  ]);
});
